title: Feather Wallet Documentation
description: A free and open source Monero desktop wallet.
baseurl: ""
url: https://docs.featherwallet.org

twitter:
  username: featherwallet
  card: summary

collections_dir: content

permalink: /:name

collections:
  guides:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /news/:title

feed:
  path: atom.xml

defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: guides
  - scope:
      path: ""
      type: posts
    values:
      layout: article
  - scope:
      path: ""
    values:
      layout: default

locale: en_GB

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - .well-known
